# Generated by Django 4.2.2 on 2023-06-28 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickerapp', '0002_alter_userrequest_user_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrequest',
            name='input_text',
            field=models.CharField(max_length=32),
        ),
    ]
